services:
  - type: web
    name: ikea-gallery-checker
    env: node
    region: oregon
    plan: starter

    buildCommand: npm install && npx puppeteer install chrome
    startCommand: npm start

    nixpacks:
      packages:
        - ca-certificates
        - fontconfig
        - freetype
        - libx11
        - libxcb
        - libxext
        - libxrender
        - libnss3
        - libgconf-2-4
        - libappindicator3-1
        - libpangocairo-1.0
        - libasound2
        - libatk1.0-0
        - libatk-bridge2.0-0
        - libcups2
        - libdrm2
        - libgbm1
        - libgtk-3-0

    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
